### ISSUE TITLE
内嵌小雅的海报强无法显示栏目

### ISSUE THREAD

**Issue by kkbeta** [power721/alist-tvbox#104]
选了Y仙女和list，都没显示电影、连续剧这些栏目。请问如何解决？

docker logs -f xiaoya-tvbox发现启动的时候有以下错误：
2023-10-23T12:03:02.134+08:00  INFO 77 --- [pool-3-thread-1] c.h.alist_tvbox.service.DoubanService    : movie data upgraded: 295.2018
2023-10-23T12:08:41.796+08:00  INFO 77 --- [nio-4567-exec-2] c.h.a.service.SubscriptionService        : remove sites: [Alist1]
2023-10-23T12:08:41.798+08:00  INFO 77 --- [nio-4567-exec-2] c.h.a.service.SubscriptionService        : replace token url in ext: http://127.0.0.1:9978/file/tvfan/token.txt+4k|fhd|auto$$$http://tvfan.xxooo.cf/
2023-10-23T12:08:41.799+08:00  INFO 77 --- [nio-4567-exec-2] c.h.a.service.SubscriptionService        : replace token url in ext: http://127.0.0.1:9978/file/tvfan/token.txt+4k|fhd|auto
2023-10-23T12:08:41.799+08:00  INFO 77 --- [nio-4567-exec-2] c.h.a.service.SubscriptionService        : replace token url in ext: http://127.0.0.1:9978/file/tvfan/token.txt+4k|fhd|auto
2023-10-23T12:08:42.466+08:00  INFO 77 --- [nio-4567-exec-5] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.

java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03B0x930x1e0xe20xf60xb90xac0xc9r0xd2/Y0xbfJ0xeaX+0xee0xebDN0x18zB0x83r0x8cP0xea0xd60xa60xd6 ]. HTTP method names must be tokens
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:407) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:264) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1740) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.11.jar:10.1.11]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

**Comment by kkbeta** [comment]
"sites": [
        {
            "ext": "xxx==",
            "filterable": 1,
            "quickSearch": 1,
            "name": "丫仙女",
            "changeable": 0,
            "jar": "https://xxxx.com:4567/spring.jar",
            "style": {
                "type": "rect"
            },
            "api": "csp_XiaoYa",
            "type": 3,
            "key": "csp_XiaoYa",
            "searchable": 1


发现https://xxxx.com:4567/spring.jar访问不了，用http就可以。https是需要在哪里配置吗？

**Comment by power721** [comment]
高级设置里面关闭： 订阅域名支持HTTPS
