### ISSUE TITLE
关于公网访问的问题，无论端口映射或者nginx反代到内网都无法播放。

### ISSUE THREAD

**Issue by SevenPlusJun** [power721/alist-tvbox#137]
请教该如何处理，
端口映射：我将4567和6789均映射到公网，手机端使用宝盒，配置好订阅能够看到索引目录信息，但任意视频均无法播放。
路由器端nginx反代到tvbox主机现象依旧。

**Comment by SevenPlusJun** [comment]
我是单独一台虚机以hostmode模式安装的。

**Comment by SevenPlusJun** [comment]
`2023-12-21T12:39:10.378+08:00  INFO 85 --- [nio-4567-exec-2] c.h.alist_tvbox.web.TvBoxController      : type: 0  path: null  folder: 1$/电影$0  keyword: null  filter: null  sort: null  page: 1
2023-12-21T12:39:33.811+08:00  INFO 85 --- [nio-4567-exec-6] c.h.alist_tvbox.web.TvBoxController      : type: 0  path: 1$/电影/2023/2023年12月份/全家变身大作战.Family Switch.2023.美国.BD1080P.英语中英双字.mp4$0  folder: null  keyword: null  filter: null  sort: null  page: 1
2023-12-21T12:39:40.994+08:00  WARN 85 --- [nio-4567-exec-6] c.h.alist_tvbox.service.AListService     : error 500 failed link: failed get link: RpcException:Failed to invoke the method isUserConsumeLimit in the service com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService. Tried 1 times of the providers [*********30:20880] (1/120) from the registry mse-bd5d2222-zk.mse.aliyuncs.com:2181 on the consumer ********10 using the dubbo version 2.6.12. Last error is: Invoke remote method timeout. method: isUserConsumeLimit, provider: dubbo://*********30:20880/com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService?__micro.service.app.id__=c576f2de-4247-45e6-bab0-60346831cabc&__micro.service.env__=[{"desc":"edas-canary","priority":-99,"tag":"183cb207cb","type":"canary"}]&anyhost=true&application=adrive-open-biz&bean.name=ServiceBean:com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService&check=false&default.check=false&default.retries=0&default.service.filter=-exception&default.timeout=3000&dubbo=2.0.2&generic=false&interface=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService&methods=isUserConsumeLimit&mse.appId=c576f2de-4247-45e6-bab0-60346831cabc&mse_aliyun_com__zone=cn-beijing-h&opensergo.io/canary=&pid=96&register.ip=********10&remote.timestamp=1702981422293&revision=********0231213-1-SNAPSHOT&side=consumer&timeout=3000&timestamp=1702618095572, cause: Waiting server-side response timeout by scan timer. start time: 2023-12-21 12:39:37.966, end time: 2023-12-21 12:39:40.977, client elapsed: 0 ms, server elapsed: 3011 ms, timeout: 3000 ms, request: Request [id=57962608, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=isUserConsumeLimit, parameterTypes=[class java.lang.String], arguments=[45214849e8f447518abc959c2b9531f7], attachments={__microservice_match_result__=[], EagleEye-pSpanID=-1, EagleEye-pAppName=95ecab6c-994e-47f9-b6e3-195b9ff3a36b, EagleEye-IP=********10, interface=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService, version=0.0.0, timeout=3000, EagleEye-UserData=__microservice_log_cur_span_id__=-1&__microservice_match_result__=[]&mse_alf=0, path=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService, EagleEye-RpcID=0.1.7, dubboApplication=adrive-open-biz, EagleEye-TraceID=0a0070d717031335775605881ec8e5, __micro.service.app.id__=95ecab6c-994e-47f9-b6e3-195b9ff3a36b, EagleEye-SpanID=-6717103063295003993, EagleEye-pRpc=/v1.0/openFile/getDownloadUrl}, attributes={serialization_id=2}]], channel: /********10:44270 -> /*********30:20880
2023-12-21T12:39:40.996+08:00 ERROR 85 --- [nio-4567-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "cn.har01d.alist_tvbox.model.FsDetail.getName()" because "fsDetail" is null] with root cause

java.lang.NullPointerException: Cannot invoke "cn.har01d.alist_tvbox.model.FsDetail.getName()" because "fsDetail" is null
        at cn.har01d.alist_tvbox.service.TvBoxService.getDetail(TvBoxService.java:1135) ~[classes/:na]
        at cn.har01d.alist_tvbox.web.TvBoxController.api(TvBoxController.java:70) ~[classes/:na]
        at cn.har01d.alist_tvbox.web.TvBoxController.api1(TvBoxController.java:43) ~[classes/:na]
        at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.16.jar:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.16.jar:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at cn.har01d.alist_tvbox.auth.TokenFilter.doFilterInternal(TokenFilter.java:52) ~[classes/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

`

**Comment by SevenPlusJun** [comment]
`WARN[2023-12-21 12:39:34] 请求失败: AccessTokenInvalid token expired
INFO[2023-12-21 12:39:36] refreshToken 1 https://auth.aliyundrive.com/v2/account/token
INFO[2023-12-21 12:39:37] refreshOpenToken 1 https://api.xhofe.top/alist/ali_open/token true
ERRO[2023-12-21 12:39:40] getOpenLink failed: RpcException:Failed to invoke the method isUserConsumeLimit in the service com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService. Tried 1 times of the providers [10.1.46.130:20880] (1/120) from the registry mse-bd5d2222-zk.mse.aliyuncs.com:2181 on the consumer 10.2.0.210 using the dubbo version 2.6.12. Last error is: Invoke remote method timeout. method: isUserConsumeLimit, provider: dubbo://10.1.46.130:20880/com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService?__micro.service.app.id__=c576f2de-4247-45e6-bab0-60346831cabc&__micro.service.env__=[{"desc":"edas-canary","priority":-99,"tag":"183cb207cb","type":"canary"}]&anyhost=true&application=adrive-open-biz&bean.name=ServiceBean:com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService&check=false&default.check=false&default.retries=0&default.service.filter=-exception&default.timeout=3000&dubbo=2.0.2&generic=false&interface=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService&methods=isUserConsumeLimit&mse.appId=c576f2de-4247-45e6-bab0-60346831cabc&mse_aliyun_com__zone=cn-beijing-h&opensergo.io/canary=&pid=96&register.ip=10.2.0.210&remote.timestamp=1702981422293&revision=1.1.11.20231213-1-SNAPSHOT&side=consumer&timeout=3000&timestamp=1702618095572, cause: Waiting server-side response timeout by scan timer. start time: 2023-12-21 12:39:37.966, end time: 2023-12-21 12:39:40.977, client elapsed: 0 ms, server elapsed: 3011 ms, timeout: 3000 ms, request: Request [id=57962608, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=isUserConsumeLimit, parameterTypes=[class java.lang.String], arguments=[45214849e8f447518abc959c2b9531f7], attachments={__microservice_match_result__=[], EagleEye-pSpanID=-1, EagleEye-pAppName=95ecab6c-994e-47f9-b6e3-195b9ff3a36b, EagleEye-IP=10.2.0.210, interface=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService, version=0.0.0, timeout=3000, EagleEye-UserData=__microservice_log_cur_span_id__=-1&__microservice_match_result__=[]&mse_alf=0, path=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService, EagleEye-RpcID=0.1.7, dubboApplication=adrive-open-biz, EagleEye-TraceID=0a0070d717031335775605881ec8e5, __micro.service.app.id__=95ecab6c-994e-47f9-b6e3-195b9ff3a36b, EagleEye-SpanID=-6717103063295003993, EagleEye-pRpc=/v1.0/openFile/getDownloadUrl}, attributes={serialization_id=2}]], channel: /10.2.0.210:44270 -> /10.1.46.130:20880
INFO[2023-12-21 12:39:40] Delete file 6583c1883de3dbd0003547e08cb61ce8230591e0 after 900 seconds.
ERRO[2023-12-21 12:39:40] failed link /电影/2023/2023年12月份/全家变身大作战.Family Switch.2023.美国.BD1080P.英语中英双字.mp4: RpcException:Failed to invoke the method isUserConsumeLimit in the service com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService. Tried 1 times of the providers [10.1.46.130:20880] (1/120) from the registry mse-bd5d2222-zk.mse.aliyuncs.com:2181 on the consumer 10.2.0.210 using the dubbo version 2.6.12. Last error is: Invoke remote method timeout. method: isUserConsumeLimit, provider: dubbo://10.1.46.130:20880/com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService?__micro.service.app.id__=c576f2de-4247-45e6-bab0-60346831cabc&__micro.service.env__=[{"desc":"edas-canary","priority":-99,"tag":"183cb207cb","type":"canary"}]&anyhost=true&application=adrive-open-biz&bean.name=ServiceBean:com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService&check=false&default.check=false&default.retries=0&default.service.filter=-exception&default.timeout=3000&dubbo=2.0.2&generic=false&interface=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService&methods=isUserConsumeLimit&mse.appId=c576f2de-4247-45e6-bab0-60346831cabc&mse_aliyun_com__zone=cn-beijing-h&opensergo.io/canary=&pid=96&register.ip=10.2.0.210&remote.timestamp=1702981422293&revision=1.1.11.20231213-1-SNAPSHOT&side=consumer&timeout=3000&timestamp=1702618095572, cause: Waiting server-side response timeout by scan timer. start time: 2023-12-21 12:39:37.966, end time: 2023-12-21 12:39:40.977, client elapsed: 0 ms, server elapsed: 3011 ms, timeout: 3000 ms, request: Request [id=57962608, version=2.0.2, twoway=true, event=false, broken=false, data=RpcInvocation [methodName=isUserConsumeLimit, parameterTypes=[class java.lang.String], arguments=[45214849e8f447518abc959c2b9531f7], attachments={__microservice_match_result__=[], EagleEye-pSpanID=-1, EagleEye-pAppName=95ecab6c-994e-47f9-b6e3-195b9ff3a36b, EagleEye-IP=10.2.0.210, interface=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService, version=0.0.0, timeout=3000, EagleEye-UserData=__microservice_log_cur_span_id__=-1&__microservice_match_result__=[]&mse_alf=0, path=com.alibaba.ic.adrive.contract.dubbo.UserCapacityDubboService, EagleEye-RpcID=0.1.7, dubboApplication=adrive-open-biz, EagleEye-TraceID=0a0070d717031335775605881ec8e5, __micro.service.app.id__=95ecab6c-994e-47f9-b6e3-195b9ff3a36b, EagleEye-SpanID=-6717103063295003993, EagleEye-pRpc=/v1.0/openFile/getDownloadUrl}, attributes={serialization_id=2}]], channel: /10.2.0.210:44270 -> /10.1.46.130:20880
failed get link
github.com/alist-org/alist/v3/internal/op.Link.func1
        /app/internal/op/fs.go:260
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
        /app/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
        /app/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
        /app/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.Link
        /app/internal/op/fs.go:270
github.com/alist-org/alist/v3/internal/fs.link
        /app/internal/fs/link.go:19
github.com/alist-org/alist/v3/internal/fs.Link
        /app/internal/fs/fs.go:48
github.com/alist-org/alist/v3/server/handles.FsGet
        /app/server/handles/fsread.go:305
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.Auth
        /app/server/middlewares/auth.go:28
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
        /app/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.LoggerWithConfig.func1
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/logger.go:240
github.com/gin-gonic/gin.(*Context).Next
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
        /root/go/pkg/mod/github.com/gin-gonic/gin@v1.9.1/gin.go:576
net/http.serverHandler.ServeHTTP
        /usr/lib/go/src/net/http/server.go:2938
net/http.(*conn).serve
        /usr/lib/go/src/net/http/server.go:2009
runtime.goexit
        /usr/lib/go/src/runtime/asm_amd64.s:1650
failed link
`

**Comment by power721** [comment]
为了解决阿里15分钟限制，替换了播放地址。公网地址必须更改站点地址为alist公网地址，才能播放。

**Comment by SevenPlusJun** [comment]
> 为了解决阿里15分钟限制，替换了播放地址。公网地址必须更改站点地址为alist公网地址，才能播放。

我在站点列表里新增alist的公网地址也不行吗？同时保留内网localhost的站点地址。


同时，我扫描发现存在未授权漏洞暴露了安全token，请修复，就不单独开case了。地址为: /token

**Comment by SevenPlusJun** [comment]
我在订阅里把json数据的内网ip全改成域名了，新增了个订阅3，使用订阅3依旧无法使用，甚至连列表都获取不到。 把域名换成我的公网ip能够获取到列表，但视频无法播放。

**Comment by WudaxStudio** [comment]
如果直接映射，理论上不会有问题的，可以正常进行访问的
