### ISSUE TITLE
大佬来看看，动漫无法播放，其它都可以，是只有我？

### ISSUE THREAD

**Issue by xiaolongzhou123** [power721/alist-tvbox#144]
通过 bash -c "$(curl -fsSL https://d.har01d.cn/update_hostmode.sh)"  搭建
本地端口4567和6789都正常运行。

就**动漫**无观看。我测试 了几十个。没有一个可以。但是通过，文件列表进入，可以播行。
是我测试 问题吗？理论上不需要怎么进行设置吧？

![1](https://github.com/power721/alist-tvbox/assets/109494974/3155b876-7ab0-497e-a41c-c400dd3dcf44)
![2](https://github.com/power721/alist-tvbox/assets/109494974/cfba83fb-112c-495a-b3fb-c7667932c2a9)

从日志上。截取了一下
2023-12-26T22:30:46.209+08:00 WARN 72 --- [http-nio-4567-exec-1] c.h.alist_tvbox.config.RestErrorHandler :
cn.har01d.alist_tvbox.exception.BadRequestException: 加载文件失败: /动漫/已刮削/2016-2020/2019/(2019)街角魔族[tmdbid=88806]/Season 1
at cn.har01d.alist_tvbox.service.TvBoxService.getPlaylist(TvBoxService.java:1210) ~[classes/:na]
at cn.har01d.alist_tvbox.service.TvBoxService.getDetail(TvBoxService.java:1101) ~[classes/:na]
at cn.har01d.alist_tvbox.web.TvBoxController.api(TvBoxController.java:70) ~[classes/:na]
at cn.har01d.alist_tvbox.web.TvBoxController.api1(TvBoxController.java:36) ~[classes/:na]
at jdk.internal.reflect.GeneratedMethodAccessor147.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.14.jar:6.0.14]
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.0.14.jar:6.0.14]
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.14.jar:6.0.14]
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.14.jar:6.0.14]
at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.16.jar:10.1.16]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110) ~[spring-web-6.0.14.jar:6.0.14]
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]

**Comment by power721** [comment]
资源失效了

**Comment by xiaolongzhou123** [comment]
大佬，你也无法播放这个是吗？
