### ISSUE TITLE
B站无法播放,显示无法获取播放地址

### ISSUE THREAD

**Issue by elven2016** [power721/alist-tvbox#155]
B站登录成功，通过vidplay添加vod的url，能获取海报墙，点击进去之后选择播放，无法播放，报错提示：无法获取播放地址，日志下载会报错无法下载，我复制出来贴到下面：
2024-01-13T19:40:26.572+08:00  INFO 48 --- [nio-4567-exec-8] c.h.alist_tvbox.web.BiliBiliController   : path: null  folder: null  keyword: null  filter: FilterDto(category=, type=, status=, sort=, duration=, year=) page: 1
2024-01-13T19:40:26.922+08:00  INFO 48 --- [nio-4567-exec-8] c.h.alist_tvbox.service.BiliBiliService  : user: Elven2022 646767664 isLogin: true vip: 2
2024-01-13T19:40:27.114+08:00  INFO 48 --- [nio-4567-exec-2] c.h.alist_tvbox.web.BiliBiliController   : path:   folder: null  keyword: null  filter: FilterDto(category=, type=, status=, sort=, duration=, year=) page: 1
2024-01-13T19:40:27.180+08:00  INFO 48 --- [nio-4567-exec-2] c.h.alist_tvbox.service.BiliBiliService  : user: Elven2022 646767664 isLogin: true vip: 2
2024-01-13T19:40:32.704+08:00  INFO 48 --- [nio-4567-exec-7] c.h.alist_tvbox.web.BiliBiliController   : path: null  folder: feed$0  keyword: null  filter: FilterDto(category=, type=, status=, sort=, duration=, year=) page: 1
2024-01-13T19:40:38.860+08:00  INFO 48 --- [nio-4567-exec-9] c.h.alist_tvbox.web.BiliBiliController   : path: BV1qk4y1Q7eP  folder: null  keyword: null  filter: FilterDto(category=, type=, status=, sort=, duration=, year=) page: 1
2024-01-13T19:40:39.185+08:00  WARN 48 --- [nio-4567-exec-9] c.h.alist_tvbox.service.BiliBiliService  : get UP playlist failed

java.lang.NullPointerException: Cannot invoke "cn.har01d.alist_tvbox.dto.bili.BiliBiliSearchInfo.getList()" because the return value of "cn.har01d.alist_tvbox.dto.bili.BiliBiliSearchInfoResponse.getData()" is null
        at cn.har01d.alist_tvbox.service.BiliBiliService.getUpPlaylist(BiliBiliService.java:800) ~[classes/:na]
        at cn.har01d.alist_tvbox.service.BiliBiliService.getDetail(BiliBiliService.java:1059) ~[classes/:na]
        at cn.har01d.alist_tvbox.web.BiliBiliController.api(BiliBiliController.java:64) ~[classes/:na]
        at cn.har01d.alist_tvbox.web.BiliBiliController.api(BiliBiliController.java:43) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.14.jar:6.0.14]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614) ~[jakarta.servlet-api-6.0.0.jar:6.0.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.security.web.FilterChainProxy.lambda$doFilterInternal$3(FilterChainProxy.java:231) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:365) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:131) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:85) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:100) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:179) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at cn.har01d.alist_tvbox.auth.TokenFilter.doFilterInternal(TokenFilter.java:52) ~[classes/:na]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:82) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.context.SecurityContextHolderFilter.doFilter(SecurityContextHolderFilter.java:69) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:62) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:233) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:191) ~[spring-security-web-6.1.5.jar:6.1.5]
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:352) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:268) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.14.jar:6.0.14]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.14.jar:6.0.14]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.16.jar:10.1.16]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]

**Comment by power721** [comment]
up主投稿列表的API鉴权失败，现在不能使用。其它接口正常。

**Comment by elven2016** [comment]
> up主投稿列表的API鉴权失败，现在不能使用。其它接口正常。

多谢，我看已经发布最新的版本是修复这个问题，但是更新后仍然是这个错误，直接更新和直接删除除后重新安装两个方式都试过了

**Comment by power721** [comment]
需要登录b站

**Comment by elven2016** [comment]
> 需要登录b站

 已经是登录状态了，还是获取播放地址失败，日志也仍然无法下载

![image](https://github.com/power721/alist-tvbox/assets/16677082/498e8b7c-c200-4a5b-87ef-af6d37607188)
2024-01-14T22:53:04.466+08:00 INFO 82 --- [http-nio-4567-exec-8] c.h.alist_tvbox.service.BiliBiliService : user: Elven2022 646767664 isLogin: true vip: 2
2024-01-14T22:54:03.704+08:00 INFO 82 --- [scheduling-1] c.h.alist_tvbox.service.AccountService : syncTokens 4
2024-01-14T22:54:03.707+08:00 INFO 82 --- [scheduling-1] c.h.alist_tvbox.service.AccountService : 1 token time: 2024-01-14T14:53:04.773674813Z 2024-01-14T14:53:05.999222608Z 2024-01-14T14:53:05.999222608Z
2024-01-14T22:55:16.305+08:00 INFO 82 --- [http-nio-4567-exec-10] c.h.alist_tvbox.web.BiliBiliController : path: null folder: null keyword: null filter: FilterDto(category=, type=, status=, sort=, duration=, year=) page: 1
2024-01-14T22:55:16.557+08:00 INFO 82 --- [http-nio-4567-exec-10] c.h.alist_tvbox.service.BiliBiliService : user: Elven2022 646767664 isLogin: true vip: 2
2024-01-14T22:55:16.657+08:00 INFO 82 --- [http-nio-4567-exec-7] c.h.alist_tvbox.web.BiliBiliController : path: folder: null keyword: null filter: FilterDto(category=, type=, status=, sort=, duration=, year=) page: 1
2024-01-14T22:55:16.729+08:00 INFO 82 --- [http-nio-4567-exec-7] c.h.alist_tvbox.service.BiliBiliService : user: Elven2022 646767664 isLogin: true vip: 2
2024-01-14T22:55:20.423+08:00 INFO 82 --- [http-nio-4567-exec-3] c.h.alist_tvbox.web.BiliBiliController : path: null folder: ups keyword: null filter: FilterDto(category=, type=, status=, sort=, duration=, year=) page: 1
2024-01-14T22:55:20.599+08:00 **ERROR 82 --- [http-ni**o-4567-exec-3] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "cn.har01d.alist_tvbox.dto.bili.BiliBiliSearchInfo.getList()" because "searchInfo" is null] with root cause
java.lang.NullPointerException: Cannot invoke "cn.har01d.alist_tvbox.dto.bili.BiliBiliSearchInfo.getList()" because "searchInfo" is null
at cn.har01d.alist_tvbox.service.BiliBiliService.getUpMedia(BiliBiliService.java:754) ~[classes/:na]
at cn.har01d.alist_tvbox.service.BiliBiliService.getMovieList(BiliBiliService.java:1514) ~[classes/:na]
at cn.har01d.alist_tvbox.web.BiliBiliController.api(BiliBiliController.java:67) ~[classes/:na]
at cn.har01d.alist_tvbox.web.BiliBiliController.api(BiliBiliController.java:43) ~[classes/:na]
at jdk.internal.reflect.GeneratedMethodAccessor202.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.15.jar:6.0.15]
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.15.jar:6.0.15]
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.15.jar:6.0.15]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.15.jar:6.0.15]
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.15.jar:6.0.15]
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.15.jar:6.0.15]

**Comment by power721** [comment]
你的UP主下面有二级分类吗？

**Comment by elven2016** [comment]
> 你的UP主下面有二级分类吗？

 没有二级分类，只有一级
![image](https://github.com/power721/alist-tvbox/assets/16677082/b820815d-5d6a-4e60-acda-3974dc935ada)

**Comment by power721** [comment]
需要加这种二级分类才行
![image](https://github.com/power721/alist-tvbox/assets/2384040/a189e8ba-9010-403e-9a05-2f38cce0d76e)

**Comment by elven2016** [comment]
> 需要加这种二级分类才行 ![image](https://private-user-images.githubusercontent.com/2384040/296664265-a189e8ba-9010-403e-9a05-2f38cce0d76e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDU4NTksIm5iZiI6MTcwNTMwNTU1OSwicGF0aCI6Ii8yMzg0MDQwLzI5NjY2NDI2NS1hMTg5ZThiYS05MDEwLTQwM2UtOWEwNS0yZjM4Y2NlMGQ3NmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTVUMDc1OTE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjgzMjMxOWZhYjkzNDhmZGFlZWQ5N2U3YjhmOTk3ZmU4ZWJjMzUzZmY1ZjhjMzM2MzhjNGRhMTg5MjQyNWQyYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cR9zgZFwRj64IJRjuMzLrE79rvmEJUJO0z6UoLlRIPQ)

多谢，可是还是一样的报错，已经添加了2个up主，再去点仍然是一样的报错，
![image](https://github.com/power721/alist-tvbox/assets/16677082/e197cbb0-761a-42b5-aa31-e2dcab9cd232)
推荐页是空白，没有添加up主之前推荐和up主都是空白，现在添加了up主后，up主页面能显示视频列了，推荐是空白，up主页面和其他所有的页面视频点击都还是一样的报错

**Comment by power721** [comment]
把错误信息发来看看

**Comment by elven2016** [comment]
> 把错误信息发来看看


我是添加到vidplay上播放，报错的情况如下
![IMG_7714](https://github.com/power721/alist-tvbox/assets/16677082/725e0923-ba0d-4e81-9215-b347e13a7abd)
![IMG_7713](https://github.com/power721/alist-tvbox/assets/16677082/691787e1-8d8a-4b9e-bfa7-711a94925698)
![IMG_7712](https://github.com/power721/alist-tvbox/assets/16677082/8fe3b22d-7600-40c9-9316-db4fb1a2e1d3)
![IMG_7711](https://github.com/power721/alist-tvbox/assets/16677082/8f972367-0c37-4f14-80bf-446c46afa5ec)

**Comment by elven2016** [comment]
> 把错误信息发来看看

今天在tvbox上测试也是不行
![IMG_7717](https://github.com/power721/alist-tvbox/assets/16677082/06289149-59b3-4c80-8e9f-1379a412eeef)
![IMG_7718](https://github.com/power721/alist-tvbox/assets/16677082/e58b5572-3b2c-47a6-b70c-e86dae1c0226)

**Comment by zhijianjianghu** [comment]
> > 把错误信息发来看看
> 
> 我是添加到vidplay上播放，报错的情况如下 ![IMG_7714](https://private-user-images.githubusercontent.com/16677082/297383555-725e0923-ba0d-4e81-9215-b347e13a7abd.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Mjk3NTcsIm5iZiI6MTcwNTcyOTQ1NywicGF0aCI6Ii8xNjY3NzA4Mi8yOTczODM1NTUtNzI1ZTA5MjMtYmEwZC00ZTgxLTkyMTUtYjM0N2UxM2E3YWJkLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwNTQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmZiMjg5N2Y2ZGU3YjBjOTU4YTUyOTE2MmVlMjNlYjU4MDdiMjNlODJjY2NhODYyYWVkM2Y2ZTBlMjI2OGRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kXSDY6r_qosrznVKU4TXrDnJbVNMG8VUvdG4k_sBUuM) ![IMG_7713](https://private-user-images.githubusercontent.com/16677082/297383573-691787e1-8d8a-4b9e-bfa7-711a94925698.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Mjk3NTcsIm5iZiI6MTcwNTcyOTQ1NywicGF0aCI6Ii8xNjY3NzA4Mi8yOTczODM1NzMtNjkxNzg3ZTEtOGQ4YS00YjllLWJmYTctNzExYTk0OTI1Njk4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwNTQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MTFiODVlNmVkYjUwMzFmZWZlZTM4OTE4YmUwMmE5MTk3YjY1MTkzNWRjMTNlZmI2OTUyYmNiNzkxZmEwYmZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ir9eNrCmsowc5buAfo8287KSIuLZy40cIz4oDjQqxwg) ![IMG_7712](https://private-user-images.githubusercontent.com/16677082/297383585-8fe3b22d-7600-40c9-9316-db4fb1a2e1d3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Mjk3NTcsIm5iZiI6MTcwNTcyOTQ1NywicGF0aCI6Ii8xNjY3NzA4Mi8yOTczODM1ODUtOGZlM2IyMmQtNzYwMC00MGM5LTkzMTYtZGI0ZmIxYTJlMWQzLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwNTQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzkwOTMxOTViMDIwOWM0ZjFkODhhOWMwOTBiNjQzZmQ4NTljMjc1NjBmZGM1ZGYxOWU5YjU1MWYzOWMyMGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1SjGZOOy2VQqBcmVNYl5axjhiSvPTnXbe3xo7HiZW50) ![IMG_7711](https://private-user-images.githubusercontent.com/16677082/297383587-8f972367-0c37-4f14-80bf-446c46afa5ec.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Mjk3NTcsIm5iZiI6MTcwNTcyOTQ1NywicGF0aCI6Ii8xNjY3NzA4Mi8yOTczODM1ODctOGY5NzIzNjctMGMzNy00ZjE0LTgwYmYtNDQ2YzQ2YWZhNWVjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyMFQwNTQ0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYzkwNzgxZmU4ZjA1YmJlOTM1M2VkYmQ4MzAxZWI4ODdhM2IyYzRkNDM0ZTQyNTQ4Y2U5YmJiYzE4MWMyZDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nLvWyofe_IOiviSk2DRFHhK8H7V6Msi-q_91OsQ4F7A)

我试了，如果显示播放列表而播放提示错误的话，那是是播放器的问题，换下播放器，比如换成EXO
