### ISSUE TITLE
今天更新之后,程序崩溃了

### ISSUE THREAD

**Issue by xiaodaidi1** [power721/alist-tvbox#225]
用的是nataive镜像

2024-02-21T07:53:10.587+08:00  WARN 125 --- [           main] w.s.c.ServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tvBoxService': Instantiation of supplied bean failed
2024-02-21T07:53:10.588+08:00  INFO 125 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2024-02-21T07:53:10.590+08:00  INFO 125 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-02-21T07:53:10.594+08:00  INFO 125 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2024-02-21T07:53:10.598+08:00  INFO 125 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-02-21T07:53:10.612+08:00 ERROR 125 --- [           main] o.s.boot.SpringApplication               : Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tvBoxService': Instantiation of supplied bean failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1220) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[atv:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[atv:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[atv:6.0.11]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[atv:3.1.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[atv:3.1.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[atv:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[atv:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[atv:3.1.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[atv:3.1.2]
	at cn.har01d.alist_tvbox.AListApplication.main(AListApplication.java:17) ~[atv:na]
Caused by: java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMS
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:90) ~[na:na]
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:40) ~[na:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3947) ~[na:na]
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3943) ~[na:na]
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1051) ~[atv:3.1.6]
	at cn.har01d.alist_tvbox.service.TvBoxService.<init>(TvBoxService.java:106) ~[atv:na]
	at cn.har01d.alist_tvbox.service.TvBoxService__BeanDefinitions.lambda$getTvBoxServiceInstanceSupplier$0(TvBoxService__BeanDefinitions.java:23) ~[na:na]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[atv:6.0.11]
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[atv:6.0.11]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:202) ~[na:na]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58) ~[atv:6.0.11]
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46) ~[atv:6.0.11]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:210) ~[na:na]
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:202) ~[na:na]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947) ~[atv:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214) ~[atv:6.0.11]
	... 17 common frames omitted
Caused by: java.lang.NoSuchMethodException: no such constructor: com.github.benmanes.caffeine.cache.SSMS.<init>(Caffeine,AsyncCacheLoader,boolean)void/newInvokeSpecial
	at java.base@17.0.7/java.lang.invoke.MemberName.makeAccessException(MemberName.java:974) ~[na:na]
	at java.base@17.0.7/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1117) ~[na:na]
	at java.base@17.0.7/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3649) ~[na:na]
	at java.base@17.0.7/java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:2750) ~[na:na]
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.loadFactory(LocalCacheFactory.java:85) ~[na:na]
	... 32 common frames omitted
Caused by: java.lang.NoSuchMethodError: com.github.benmanes.caffeine.cache.SSMS.<init>(com.github.benmanes.caffeine.cache.Caffeine, com.github.benmanes.caffeine.cache.AsyncCacheLoader, boolean)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandleNatives.resolve(Target_java_lang_invoke_MethodHandleNatives.java:345) ~[na:na]
	at java.base@17.0.7/java.lang.invoke.MethodHandleNatives.resolve(MethodHandleNatives.java:223) ~[na:na]
	at java.base@17.0.7/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:1085) ~[na:na]
	at java.base@17.0.7/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1114) ~[na:na]
	... 35 common frames omitted

**Comment by Akikazehub** [comment]
同样是今天更新后无法运行，native

**Comment by f0re1gnKey** [comment]
同样是今天更新后无法运行，native-host

**Comment by Akikazehub** [comment]
测试包括lastest及dev等都全部运行不了
