### ISSUE TITLE
无限重启

### ISSUE THREAD

**Issue by nick200000** [power721/alist-tvbox#38]
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: "/data/atv.mv.db". Possible solution: use the recovery tool [90030-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:678) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.message.DbException.get(DbException.java:212) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:166) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.db.Store.<init>(Store.java:145) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.engine.Database.<init>(Database.java:324) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.engine.Engine.openSession(Engine.java:92) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.engine.Engine.openSession(Engine.java:222) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.engine.Engine.createSession(Engine.java:201) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.Driver.connect(Driver.java:59) ~[h2-2.1.214.jar:2.1.214]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:na]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:na]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:na]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:na]
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:na]
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:181) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:44) ~[hibernate-core-5.6.15.Final.jar:5.6.15.Final]
        ... 102 common frames omitted
Caused by: org.h2.mvstore.MVStoreException: Double mark: 1337/255 [2-3, a-1c, 3b-40, 48-232, 262-263, 269-26e, 278-27b, 2b5-2b7, 2cc-300, 31f-321, 329-32f, 34b-35f, 365-365, 381-396, 3b4-3b4, 3c6-3c7, 409-40f, 430-6b0, 6da-6da, c15-c28, c3c-c4a, cc6-cc7, cdf-d40, 1337-1444, 1623-16bd, 1b3a-1c0a, 1e19-1e47, 20b4-2143, 2943-] [2.1.214/6]
        at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.FreeSpaceBitSet.markUsed(FreeSpaceBitSet.java:184) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.FileStore.markUsed(FileStore.java:344) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:1052) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore.<init>(MVStore.java:463) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4082) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.db.Store.<init>(Store.java:136) ~[h2-2.1.214.jar:2.1.214]
        ... 119 common frames omitted
跑到这里就自动重启了~~

**Comment by power721** [comment]
把这个数据库atv.mv.db删了重启吧
