### ISSUE TITLE
一直重启？怎么回事呢

### ISSUE THREAD

**Issue by xiankaiyao** [power721/alist-tvbox#59]
stdout: 已经初始化成功
stdout: 
stdout:   .   ____          _            __ _ _
stdout:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
stdout: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
stdout:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
stdout:   '  |____| .__|_| |_|_| |_\__, | / / / /
stdout:  =========|_|==============|___/=/_/_/_/
stdout:  :: Spring Boot ::                (v3.1.2)
stdout: 
stdout: 2023-08-27T12:05:32.767+08:00  INFO 17 --- [           main] cn.har01d.alist_tvbox.AListApplication   : Starting AListApplication using Java 17.0.8 with PID 17 (/opt/atv/BOOT-INF/classes started by root in /opt/atv)
stdout: 2023-08-27T12:05:32.832+08:00  INFO 17 --- [           main] cn.har01d.alist_tvbox.AListApplication   : The following 2 profiles are active: "production", "xiaoya"
stdout: 2023-08-27T12:05:42.096+08:00  INFO 17 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
stdout: 2023-08-27T12:05:43.340+08:00  INFO 17 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1149 ms. Found 15 JPA repository interfaces.
stdout: 2023-08-27T12:05:50.986+08:00  INFO 17 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 4567 (http)
stdout: 2023-08-27T12:05:51.104+08:00  INFO 17 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
stdout: 2023-08-27T12:05:51.110+08:00  INFO 17 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.11]
stdout: 2023-08-27T12:05:52.251+08:00  INFO 17 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
stdout: 2023-08-27T12:05:52.255+08:00  INFO 17 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 18507 ms
stdout: 2023-08-27T12:05:54.243+08:00  INFO 17 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
stdout: 2023-08-27T12:05:54.768+08:00  INFO 17 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.2.6.Final
stdout: 2023-08-27T12:05:54.792+08:00  INFO 17 --- [           main] org.hibernate.cfg.Environment            : HHH000406: Using bytecode reflection optimizer
stdout: 2023-08-27T12:05:56.097+08:00  INFO 17 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
stdout: 2023-08-27T12:05:57.361+08:00  INFO 17 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
stdout: 2023-08-27T12:05:57.484+08:00  INFO 17 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
stdout: 2023-08-27T12:05:59.927+08:00  INFO 17 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection conn0: url=jdbc:h2:file:/data/atv user=SA
stdout: 2023-08-27T12:05:59.959+08:00  INFO 17 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
stdout: 2023-08-27T12:06:03.242+08:00  INFO 17 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [subscription]
stdout: 2023-08-27T12:06:03.310+08:00  INFO 17 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [site]
stdout: 2023-08-27T12:06:03.315+08:00  INFO 17 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [navigation]
stdout: 2023-08-27T12:06:03.321+08:00  INFO 17 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [task]
stdout: 2023-08-27T12:06:03.326+08:00  INFO 17 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [index_template]
stdout: 2023-08-27T12:06:03.331+08:00  INFO 17 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [pik_pak_account]
stdout: 2023-08-27T12:06:03.450+08:00  INFO 17 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
stdout: 2023-08-27T12:06:13.114+08:00  INFO 17 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
stdout: 2023-08-27T12:06:13.828+08:00  INFO 17 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
stderr: Error: stepping, UNIQUE constraint failed: x_setting_items.key (19)
stdout: 2023-08-27T12:06:25.189+08:00  WARN 17 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AListAliasService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListAliasService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'accountService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AccountService.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'indexService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/IndexService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'AListService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'siteService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/SiteService.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: No data scripts found at location 'file:/data/atv/data.sql'
stdout: 2023-08-27T12:06:25.200+08:00  INFO 17 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
stdout: 2023-08-27T12:06:25.229+08:00  INFO 17 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
stdout: 2023-08-27T12:06:25.358+08:00  INFO 17 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
stdout: 2023-08-27T12:06:25.383+08:00  INFO 17 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
stdout: 2023-08-27T12:06:25.532+08:00  INFO 17 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
stdout: 
stdout: Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
stdout: 2023-08-27T12:06:25.705+08:00 ERROR 17 --- [           main] o.s.boot.SpringApplication               : Application run failed
stdout: 
stdout: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AListAliasService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListAliasService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'accountService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AccountService.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'indexService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/IndexService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'AListService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'siteService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/SiteService.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: No data scripts found at location 'file:/data/atv/data.sql'
stdout: 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:245) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1189) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.11.jar:6.0.11]
stdout: 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.2.jar:3.1.2]
stdout: 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.2.jar:3.1.2]
stdout: 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.2.jar:3.1.2]
stdout: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.2.jar:3.1.2]
stdout: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.2.jar:3.1.2]
stdout: 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.2.jar:3.1.2]
stdout: 	at cn.har01d.alist_tvbox.AListApplication.main(AListApplication.java:17) ~[classes/:na]

**Comment by power721** [comment]
把这个文件删除了：
/etc/xiaoya/atv/base_version

**Comment by xiankaiyao** [comment]
没有这个文件。。。
我看错误是这个：
stderr: Error: stepping, UNIQUE constraint failed: x_setting_items.key (19)
stdout: 2023-08-27T12:46:08.850+08:00  WARN 18 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AListAliasService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListAliasService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'accountService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AccountService.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'indexService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/IndexService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'AListService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'siteService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/SiteService.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: No data scripts found at location 'file:/data/atv/data.sql'
stdout: 2023-08-27T12:46:08.856+08:00  INFO 18 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
stdout: 2023-08-27T12:46:08.874+08:00  INFO 18 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
stdout: 2023-08-27T12:46:09.125+08:00  INFO 18 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
stdout: 2023-08-27T12:46:09.142+08:00  INFO 18 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
stdout: 2023-08-27T12:46:09.270+08:00  INFO 18 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 
stdout: 
stdout: Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
stdout: 2023-08-27T12:46:09.391+08:00 ERROR 18 --- [           main] o.s.boot.SpringApplication               : Application run failed
stdout: 
stdout: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'AListAliasService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListAliasService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'accountService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AccountService.class]: Unsatisfied dependency expressed through constructor parameter 4: Error creating bean with name 'indexService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/IndexService.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'AListService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/AListService.class]: Unsatisfied dependency expressed through constructor parameter 1: Error creating bean with name 'siteService' defined in file [/opt/atv/BOOT-INF/classes/cn/har01d/alist_tvbox/service/SiteService.class]: Unsatisfied dependency expressed through constructor parameter 3: Error creating bean with name 'dataSourceScriptDatabaseInitializer' defined in class path resource [org/springframework/boot/autoconfigure/sql/init/DataSourceInitializationConfiguration.class]: No data scripts found at location 'file:/data/atv/data.sql'

**Comment by power721** [comment]
全部删掉，重新安装
