### ISSUE TITLE
订阅地址报错

### ISSUE THREAD

**Issue by caipeizhi** [power721/alist-tvbox#74]
访问：http://ip:4567/sub/0
提示：
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sat Sep 09 23:19:59 CST 2023
There was an unexpected error (type=Internal Server Error, status=500).
Cannot invoke "String.split(String)" because "apiUrl" is null

**Comment by caipeizhi** [comment]
日志：
2023-09-09T23:17:44.497+08:00 ERROR 49 --- [http-nio-4567-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "apiUrl" is null] with root cause
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "apiUrl" is null
at cn.har01d.alist_tvbox.service.SubscriptionService.subscription(SubscriptionService.java:264) ~[classes/:na]
at cn.har01d.alist_tvbox.service.SubscriptionService.subscription(SubscriptionService.java:259) ~[classes/:na]
at cn.har01d.alist_tvbox.web.TvBoxController.subscription(TvBoxController.java:111) ~[classes/:na]
at cn.har01d.alist_tvbox.web.TvBoxController.subscription(TvBoxController.java:102) ~[classes/:na]
at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-6.0.11.jar:6.0.11]
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-6.0.11.jar:6.0.11]

**Comment by power721** [comment]
编辑一下订阅
