### ISSUE TITLE
无限重启

### ISSUE THREAD

**Issue by choateyang** [power721/alist-tvbox#94]
```
279.1330
管理索引文件
Fri Oct  6 15:24:24 CST 2023
已经初始化成功
Connecting to docker.xiaoya.pro (172.67.178.229:80)
saving to 'update.zip'
update.zip            32% |**********                      |  439k  0:00:02 ETA
update.zip           100% |********************************| 1366k  0:00:00 ETA
'update.zip' saved
Fri Oct  6 15:24:27 CST 2023 total 186 records
Fri Oct  6 15:24:28 CST 2023 update database successfully
index version: 0.6.92 0.6.92
Fri Oct  6 15:24:28 CST 2023 current index file version is updated, no need to upgrade
share index version: 278.1118 278.1118
movie base version: 0.0 279.0921
Connecting to data.har01d.cn (1.15.122.161:80)
saving to 'data.zip'
data.zip               0% |                                | 33888  0:06:12 ETA
data.zip               1% |                                |  242k  0:01:39 ETA
data.zip               3% |*                               |  450k  0:01:19 ETA
data.zip               5% |*                               |  696k  0:01:06 ETA
data.zip               9% |**                              | 1144k  0:00:48 ETA
data.zip              12% |***                             | 1493k  0:00:43 ETA
data.zip              14% |****                            | 1773k  0:00:41 ETA
data.zip              15% |*****                           | 1971k  0:00:42 ETA
data.zip              17% |*****                           | 2184k  0:00:41 ETA
data.zip              20% |******                          | 2484k  0:00:39 ETA
data.zip              22% |*******                         | 2822k  0:00:37 ETA
data.zip              25% |********                        | 3098k  0:00:35 ETA
data.zip              26% |********                        | 3323k  0:00:35 ETA
data.zip              28% |*********                       | 3476k  0:00:35 ETA
data.zip              29% |*********                       | 3593k  0:00:36 ETA
data.zip              30% |*********                       | 3803k  0:00:35 ETA
data.zip              32% |**********                      | 4018k  0:00:35 ETA
data.zip              34% |**********                      | 4240k  0:00:34 ETA
data.zip              35% |***********                     | 4423k  0:00:33 ETA
data.zip              37% |************                    | 4673k  0:00:32 ETA
data.zip              38% |************                    | 4802k  0:00:32 ETA
data.zip              39% |************                    | 4874k  0:00:33 ETA
data.zip              40% |************                    | 4944k  0:00:34 ETA
data.zip              40% |************                    | 5006k  0:00:35 ETA
data.zip              41% |*************                   | 5067k  0:00:35 ETA
data.zip              41% |*************                   | 5108k  0:00:36 ETA
data.zip              41% |*************                   | 5159k  0:00:37 ETA
data.zip              42% |*************                   | 5208k  0:00:38 ETA
data.zip              42% |*************                   | 5261k  0:00:39 ETA
data.zip              42% |*************                   | 5297k  0:00:39 ETA
data.zip              43% |*************                   | 5363k  0:00:40 ETA
data.zip              44% |**************                  | 5449k  0:00:40 ETA
data.zip              45% |**************                  | 5631k  0:00:39 ETA
data.zip              47% |***************                 | 5828k  0:00:37 ETA
data.zip              48% |***************                 | 6029k  0:00:36 ETA
data.zip              50% |****************                | 6225k  0:00:35 ETA
data.zip              52% |****************                | 6458k  0:00:33 ETA
data.zip              54% |*****************               | 6665k  0:00:32 ETA
data.zip              56% |******************              | 7013k  0:00:29 ETA
data.zip              58% |******************              | 7264k  0:00:27 ETA
data.zip              60% |*******************             | 7508k  0:00:26 ETA
data.zip              62% |********************            | 7772k  0:00:24 ETA
data.zip              64% |********************            | 8015k  0:00:23 ETA
data.zip              66% |*********************           | 8210k  0:00:22 ETA
data.zip              68% |*********************           | 8409k  0:00:21 ETA
data.zip              70% |**********************          | 8645k  0:00:19 ETA
data.zip              71% |**********************          | 8866k  0:00:18 ETA
data.zip              73% |***********************         | 9029k  0:00:17 ETA
data.zip              73% |***********************         | 9099k  0:00:17 ETA
data.zip              74% |***********************         | 9219k  0:00:16 ETA
data.zip              75% |************************        | 9331k  0:00:16 ETA
data.zip              76% |************************        | 9460k  0:00:15 ETA
data.zip              77% |************************        | 9553k  0:00:15 ETA
data.zip              77% |************************        | 9616k  0:00:15 ETA
data.zip              78% |*************************       | 9708k  0:00:14 ETA
data.zip              79% |*************************       | 9845k  0:00:14 ETA
data.zip              80% |*************************       | 9908k  0:00:13 ETA
data.zip              80% |*************************       | 9962k  0:00:13 ETA
data.zip              81% |*************************       |  9.7M  0:00:13 ETA
data.zip              81% |**************************      |  9.8M  0:00:13 ETA
data.zip              82% |**************************      |  9.9M  0:00:13 ETA
data.zip              82% |**************************      |  9.9M  0:00:13 ETA
data.zip              82% |**************************      |  9.9M  0:00:13 ETA
data.zip              83% |**************************      | 10.0M  0:00:13 ETA
data.zip              83% |**************************      | 10.0M  0:00:12 ETA
data.zip              84% |**************************      | 10.1M  0:00:12 ETA
data.zip              84% |***************************     | 10.2M  0:00:12 ETA
data.zip              85% |***************************     | 10.2M  0:00:11 ETA
data.zip              86% |***************************     | 10.3M  0:00:11 ETA
data.zip              86% |***************************     | 10.4M  0:00:10 ETA
data.zip              87% |****************************    | 10.5M  0:00:09 ETA
data.zip              89% |****************************    | 10.7M  0:00:08 ETA
data.zip              90% |****************************    | 10.8M  0:00:07 ETA
data.zip              91% |*****************************   | 11.0M  0:00:06 ETA
data.zip              92% |*****************************   | 11.1M  0:00:06 ETA
data.zip              92% |*****************************   | 11.1M  0:00:05 ETA
data.zip              93% |*****************************   | 11.2M  0:00:05 ETA
data.zip              93% |*****************************   | 11.2M  0:00:05 ETA
data.zip              93% |******************************  | 11.3M  0:00:05 ETA
data.zip              94% |******************************  | 11.3M  0:00:04 ETA
data.zip              94% |******************************  | 11.3M  0:00:04 ETA
data.zip              94% |******************************  | 11.4M  0:00:04 ETA
data.zip              95% |******************************  | 11.5M  0:00:03 ETA
data.zip              97% |******************************* | 11.6M  0:00:02 ETA
data.zip              98% |******************************* | 11.8M  0:00:01 ETA
data.zip             100% |********************************| 12.0M  0:00:00 ETA
'data.zip' saved

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.1.2)

2023-10-06T15:25:55.055+08:00  INFO 58 --- [           main] cn.har01d.alist_tvbox.AListApplication   : Starting AListApplication using Java 17.0.8 with PID 58 (/opt/atv/BOOT-INF/classes started by root in /opt/atv)
2023-10-06T15:25:55.058+08:00  INFO 58 --- [           main] cn.har01d.alist_tvbox.AListApplication   : The following 2 profiles are active: "production", "xiaoya"
2023-10-06T15:25:56.048+08:00  INFO 58 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2023-10-06T15:25:56.177+08:00  INFO 58 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 119 ms. Found 15 JPA repository interfaces.
2023-10-06T15:25:57.019+08:00  INFO 58 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 4567 (http)
2023-10-06T15:25:57.032+08:00  INFO 58 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2023-10-06T15:25:57.033+08:00  INFO 58 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.11]
2023-10-06T15:25:57.179+08:00  INFO 58 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2023-10-06T15:25:57.180+08:00  INFO 58 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2053 ms
2023-10-06T15:25:57.379+08:00  INFO 58 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2023-10-06T15:25:57.442+08:00  INFO 58 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 6.2.6.Final
2023-10-06T15:25:57.444+08:00  INFO 58 --- [           main] org.hibernate.cfg.Environment            : HHH000406: Using bytecode reflection optimizer
2023-10-06T15:25:57.618+08:00  INFO 58 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-10-06T15:25:57.764+08:00  INFO 58 --- [           main] o.s.o.j.p.SpringPersistenceUnitInfo      : No LoadTimeWeaver setup: ignoring JPA class transformer
2023-10-06T15:25:57.782+08:00  INFO 58 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2023-10-06T15:25:58.113+08:00  INFO 58 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection conn0: url=jdbc:h2:file:/data/atv user=SA
2023-10-06T15:25:58.115+08:00  INFO 58 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2023-10-06T15:25:58.425+08:00  INFO 58 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [subscription]
2023-10-06T15:25:58.431+08:00  INFO 58 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [meta]
2023-10-06T15:25:58.432+08:00  INFO 58 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [site]
2023-10-06T15:25:58.432+08:00  INFO 58 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [navigation]
2023-10-06T15:25:58.433+08:00  INFO 58 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [task]
2023-10-06T15:25:58.433+08:00  INFO 58 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [index_template]
2023-10-06T15:25:58.433+08:00  INFO 58 --- [           main] o.hibernate.id.enhanced.TableGenerator   : HHH000398: Explicit segment value for id generator [id_generator.entity_name] suggested; using default [pik_pak_account]
2023-10-06T15:25:58.449+08:00  INFO 58 --- [           main] o.h.b.i.BytecodeProviderInitiator        : HHH000021: Bytecode provider name : bytebuddy
2023-10-06T15:25:59.408+08:00  INFO 58 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2023-10-06T15:25:59.484+08:00  INFO 58 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2023-10-06T15:26:04.767+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.SiteService      : set site url 丫仙女: http://localhost
2023-10-06T15:26:05.009+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.AccountService   : schedule time: 09:00
2023-10-06T15:26:05.029+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.AccountService   : load account from files
2023-10-06T15:26:05.031+08:00  WARN 58 --- [           main] c.h.alist_tvbox.service.AccountService   : No account
2023-10-06T15:26:05.045+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.AccountService   : enable AList guest
2023-10-06T15:26:05.052+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.AccountService   : disable AList user 
Error: stepping, UNIQUE constraint failed: x_users.id (19)
2023-10-06T15:26:05.142+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.ShareService     : update storage driver type
2023-10-06T15:26:05.649+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.ShareService     : Tacit0924 link: Rbb6hP91JXR
2023-10-06T15:26:06.201+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.ShareService     : insert Share 7001 mxAfB6eRgY4: /🈴我的阿里分享/近期更新, result: 0
2023-10-06T15:26:06.208+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.ShareService     : insert Share 7000 Rbb6hP91JXR: /🈴我的阿里分享/Tacit0924, result: 0
2023-10-06T15:26:06.425+08:00  INFO 58 --- [           main] c.h.alist_tvbox.service.DoubanService    : fix meta id
2023-10-06T15:26:06.435+08:00  WARN 58 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'doubanService': Invocation of init method failed
2023-10-06T15:26:06.437+08:00  INFO 58 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2023-10-06T15:26:06.440+08:00  INFO 58 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2023-10-06T15:26:06.872+08:00  INFO 58 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2023-10-06T15:26:06.874+08:00  INFO 58 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2023-10-06T15:26:06.899+08:00  INFO 58 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-10-06T15:26:06.930+08:00 ERROR 58 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'doubanService': Invocation of init method failed
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:222) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1762) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[spring-context-6.0.11.jar:6.0.11]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[spring-context-6.0.11.jar:6.0.11]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.2.jar:3.1.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.2.jar:3.1.2]
        at cn.har01d.alist_tvbox.AListApplication.main(AListApplication.java:17) ~[classes/:na]
Caused by: org.springframework.dao.DuplicateKeyException: StatementCallback; SQL [INSERT INTO ID_GENERATOR VALUES ('meta', 500000)]; Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_1 ON PUBLIC.ID_GENERATOR(ENTITY_NAME) VALUES ( /* 2 */ 'meta' )"; SQL statement:
INSERT INTO ID_GENERATOR VALUES ('meta', 500000) [23505-214]
        at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:93) ~[spring-jdbc-6.0.11.jar:6.0.11]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-6.0.11.jar:6.0.11]
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1580) ~[spring-jdbc-6.0.11.jar:6.0.11]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:398) ~[spring-jdbc-6.0.11.jar:6.0.11]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:436) ~[spring-jdbc-6.0.11.jar:6.0.11]
        at cn.har01d.alist_tvbox.service.DoubanService.fixMetaId(DoubanService.java:158) ~[classes/:na]
        at cn.har01d.alist_tvbox.service.DoubanService.setup(DoubanService.java:150) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMethod.invoke(InitDestroyAnnotationBeanPostProcessor.java:457) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:401) ~[spring-beans-6.0.11.jar:6.0.11]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:219) ~[spring-beans-6.0.11.jar:6.0.11]
        ... 18 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_1 ON PUBLIC.ID_GENERATOR(ENTITY_NAME) VALUES ( /* 2 */ 'meta' )"; SQL statement:
INSERT INTO ID_GENERATOR VALUES ('meta', 500000) [23505-214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:508) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.index.Index.getDuplicateKeyException(Index.java:525) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.command.dml.Insert.insertRows(Insert.java:174) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.command.dml.Insert.update(Insert.java:135) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.command.Command.executeUpdate(Command.java:252) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252) ~[h2-2.1.214.jar:2.1.214]
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223) ~[h2-2.1.214.jar:2.1.214]
        at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-5.0.1.jar:na]
        at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-5.0.1.jar:na]
        at org.springframework.jdbc.core.JdbcTemplate$1ExecuteStatementCallback.doInStatement(JdbcTemplate.java:427) ~[spring-jdbc-6.0.11.jar:6.0.11]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:383) ~[spring-jdbc-6.0.11.jar:6.0.11]
        ... 28 common frames omitted
```

docker全部删了一次还是不行

**Comment by power721** [comment]
重新升级安装

**Comment by choateyang** [comment]
`sudo bash -c "$(curl -fsSL https://d.har01d.cn/update_xiaoya.sh)"`

用的一键脚本，还有办法升级吗？

**Comment by jokerknight** [comment]
使用 docker compose 安装遇到同样的问题，无限重启，报错是 YamlProcessor 找不到，重装之后隔一段时间就会莫名其妙出现问题，能否保持稳定性？
